### ISSUE TITLE
Building errors

### ISSUE THREAD

**Issue by Thanh-Binh** [VLOGroup/dvs-panotracking#1]
by runing cmake ../src, I got the following errors:
Unknown CMake command "cuda_add_library".
Cannot specify link libraries for target "dvs-tracking-common" which is not
  built by this project.

Could you help me?

**Comment by reini1305** [comment]
Can you post the whole error message? It looks like CUDA could not be found by CMake.

**Comment by Thanh-Binh** [comment]
Here is the whole error:
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:17 (cuda_include_directories):
  Unknown CMake command "cuda_include_directories".


-- Configuring incomplete, errors occurred!
See also "/home/binh/Neuromorphics/dvs-panotracking/build/CMakeFiles/CMakeOutput.log".

**Comment by reini1305** [comment]
Hm, in CMakeLists.txt:16 the image utilities should be included. Looks like they can't be found. Did you install them with `make install`? And where is IMAGEUTILITIES_ROOT pointing to?

**Comment by Thanh-Binh** [comment]
yes, even with sudo make install.

Good question where IMAGEUTILITIES_ROOT points to? include or lib subfolder?
In my cases I set
export IMAGEUTILITIES_ROOT=/home/binh/Neuromorphics/dvs-panotracking/imageutilities/

**Comment by reini1305** [comment]
The IMAGEUTILITIES_ROOT should be set to the install folder (or conversely, iu will install itself into this destination if it is set before executing CMake for the first time). If iu ended up in `/usr/local`(which is the default), then you should try to set the variable to that folder.

**Comment by Thanh-Binh** [comment]
There is no indtall folder for imageutility. After doing "sudo make install" all header files are copied into /usr/local/include/iu/ and lib into /usr/local/lib. Could you pls tell me how the install folder of imageutilities does look like? If it contains subfolder like "include" and " lib", i will create them manually!

**Comment by reini1305** [comment]
Please try to set it to `/usr/local/` then.

**Comment by Thanh-Binh** [comment]
I set it, but have the same errors:
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:17 (cuda_include_directories):
  Unknown CMake command "cuda_include_directories".


-- Configuring incomplete, errors occurred!
See also "/home/binh/Neuromorphics/dvs-panotracking/build/CMakeFiles/CMakeOutput.log".

I think, it is a problem with cuda in my Ubuntu...but I really do not find out where the definition of "cuda_include_directories" is? Could you show me?

**Comment by reini1305** [comment]
Well, this is hard to debug without access to the machine. Please try to start over again with image utilities, deleting the CMakeCache, setting the IMAGEUTILITIES_ROOT before running CMake, checking the install location with ccmake or cmake-gui to be the location of your image utilities installation (in your case /home/binh/Neuromorphics/dvs-panotracking/imageutilities/). 

After all of this works, please try dvs_panotracking again.

Sorry that this doesn't work for you. I've tested it successfully on a fresh installation of Ubuntu 14.04 and 16.04 with no issues.

**Comment by Thanh-Binh** [comment]
I installed again imageutilities, it is better, but I have another error with
"Cannot specify link libraries for target "dvs-tracking-common" which is not
  built by this project"
 like:
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda-8.0 (found suitable version "8.0", minimum required is "5.0") 
-- Imageutilities requested components: iucore;iuio;iumath;iugui
-- ImageUtilities using iuio, adding OpenCV as dependency
Enabling fixes for OpenCV >= 3
-- Found Imageutilities: /home/binh/Neuromorphics/dvs-panotracking/imageutilities/lib /home/binh/Neuromorphics/dvs-panotracking/imageutilities/include;/usr/local/cuda-8.0/samples/common/inc
CMake Error at CMakeLists.txt:57 (target_link_libraries):
  Cannot specify link libraries for target "dvs-tracking-common" which is not
  built by this project.


-- Configuring incomplete, errors occurred!
See also "/home/binh/Neuromorphics/dvs-panotracking/build/CMakeFiles/CMakeOutput.log".
See also "/home/binh/Neuromorphics/dvs-panotracking/build/CMakeFiles/CMakeError.log".

**Comment by reini1305** [comment]
Looks like some artefacts from your last build. Try to start fresh by deleting the CMake cache and/or the build folder.

**Comment by Thanh-Binh** [comment]
No, i deleted all in this folder and created completely new.

**Comment by Thanh-Binh** [comment]
I found a mistake myself, so that compilation was done. I close this issue. Thanks for your support!

**Comment by reini1305** [comment]
Glad that it worked out for you! Can you describe what you did, just in case someone else has the same problem.

**Comment by Thanh-Binh** [comment]
after using original cmakefile.txt, it works

**Comment by Thanh-Binh** [comment]
Do you have any sample of a camera calibration file so that i can run the first test?

**Comment by reini1305** [comment]
Please check the data/ folder and the README :)

**Comment by Thanh-Binh** [comment]
I see thanks
