### ISSUE TITLE
error: no matching function for call to  npy_save

### ISSUE THREAD

**Issue by ccs-ros** [VLOGroup/dvs-panotracking#2]
I encouraged a problem when i use the command "make -j6" ,here is the error message:

/home/ccs/dvs-panotracking/src/common.cpp:131:63: error: no matching function for call to ‘npy_save(std::basic_string, float*, const unsigned int [2], int)’
cnpy::npy_save(filename + ".npy",in_cpu.data(),shape,2);
^
In file included from /home/ccs/dvs-panotracking/src/common.cpp:20:0:
/usr/local/include/cnpy.h:88:31: note: candidate: template void cnpy::npy_save(std::string, const T*, std::vector, std::string)
template void npy_save(std::string fname, const T* data, const std::vect
^
/usr/local/include/cnpy.h:88:31: note: template argument deduction/substitution failed:
/home/ccs/dvs-panotracking/src/common.cpp:131:63: note: cannot convert ‘shape’ (type ‘const unsigned int [2]’) to type ‘std::vector’
cnpy::npy_save(filename + ".npy",in_cpu.data(),shape,2);
^
In file included from /home/ccs/dvs-panotracking/src/common.cpp:20:0:
/usr/local/include/cnpy.h:223:31: note: candidate: template void cnpy::npy_save(std::string, std::vector, std::string)
template void npy_save(std::string fname, const std::vector data, std
^
/usr/local/include/cnpy.h:223:31: note: template argument deduction/substitution failed:
/home/ccs/dvs-panotracking/src/common.cpp:131:63: note: mismatched types ‘std::vector’ and ‘float*’
cnpy::npy_save(filename + ".npy",in_cpu.data(),shape,2);
^
/home/ccs/dvs-panotracking/src/common.cpp: In function ‘void saveState(std::string, const ImageGpu_8u_C4*)’:
/home/ccs/dvs-panotracking/src/common.cpp:148:38: warning: narrowing conversion of ‘sz.intn<2>::.special::intn<2>::width’ from ‘int’ to ‘unsigned int’ inside { } [-Wnarrowing]
const unsigned int shape[] = {sz.width,sz.height};
^
/home/ccs/dvs-panotracking/src/common.cpp:148:47: warning: narrowing conversion of ‘sz.intn<2>::.special::intn<2>::height’ from ‘int’ to ‘unsigned int’ inside { } [-Wnarrowing]
const unsigned int shape[] = {sz.width,sz.height};
^
make[2]: *** [CMakeFiles/dvs-tracking-common.dir/common.cpp.o] Error 1
make[1]: *** [CMakeFiles/dvs-tracking-common.dir/all] Error 2
make: *** [all] Error 2

please give me some solusions,thank you very much!

**Comment by reini1305** [comment]
It looks like the cnpy interface changed once again. We include a bundled version which can be used with panotracking, and you can make sure to build the correct version by checking out the repository with the switch --recursive.

If you need a different version of cnpy on your system, I'm happy to accept a PR :)

**Comment by ccs-ros** [comment]
@reini1305 I solved this problem. It is indeed a version issue. Thank you very much.And it looks like the URL(https://github.com/rogersce/cnpy.git) doesn't connect to the file on the current page,i solved the problem by copy these file to my table of contents.

**Comment by ccs-ros** [comment]
@reini1305 i encourage a new problem,i used the command "./live_tracking_gui camera_calibration_file.txt",and here is the error message:
found 1 devices
device number=0 info= GeForce GTX 1060 6GB
terminate called after throwing an instance of 'IuCudaException'
  what():  IuException: CUDA Error: out of memory
      where: /home/ccs/dvs-panotracking/imageutilities/include/iu/iucore/image_allocator_gpu.h | alloc:21
Aborted (core dumped)

i don't know how to address this,please help me and give me some guidance.thank you!

**Comment by reini1305** [comment]
I'll close this issue and start a new one for this: #3
