### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by reini1305** [VLOGroup/dvs-panotracking#3]
@reini1305 i encourage a new problem,i used the command "./live_tracking_gui camera_calibration_file.txt",and here is the error message:
found 1 devices
device number=0 info= GeForce GTX 1060 6GB
terminate called after throwing an instance of 'IuCudaException'
what(): IuException: CUDA Error: out of memory
where: /home/ccs/dvs-panotracking/imageutilities/include/iu/iucore/image_allocator_gpu.h | alloc:21
Aborted (core dumped)

i don't know how to address this,please help me and give me some guidance.thank you!

**Comment by reini1305** [comment]
This will be hard to debug remotely. The error most likely has nothing to do with memory allocation itself, but CUDA code not running in general.

@ccs-ros can you give me more details about your hardware/software configuration

**Comment by ccs-ros** [comment]
@reini1305 ok,about the software,my system is ubuntu14.04,i installed cmake(3.2.2),Qt5.8,gcc(5.4.1),g++(5.4.1),cuda(8.0),opencv(3.1.0),openexr(1.7.0),ilmbase(1.0.2);my video card is GeForce GTX 1060.

**Comment by reini1305** [comment]
OK, this seems to be alright. The only difference is, that I tried it on Ubuntu 16.04 (but 14.04 should be fine as well).

Do you have any way to test if any other CUDA application is working on your machine? And can you post the output of nvidia-smi?

**Comment by reini1305** [comment]
OK, this seems to be alright. The only difference is, that I tried it on Ubuntu 16.04 (but 14.04 should be fine as well).

Do you have any way to test if any other CUDA application is working on your machine? And can you post the output of nvidia-smi?

**Comment by ccs-ros** [comment]
@reini1305 here is the nvidia-smi in my computer:
Fri Apr 27 16:23:02 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.26                 Driver Version: 375.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 0000:01:00.0      On |                  N/A |
| 27%   40C    P0    27W / 120W |    114MiB /  6071MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1108    G   /usr/lib/xorg/Xorg                             112MiB |
+-----------------------------------------------------------------------------+
Currently,i have not installed other  CUDA application.

**Comment by ccs-ros** [comment]
@reini1305 i do not know what aspect should i start to debug it,can you give me some advice?thank you!
