### ISSUE TITLE
iugui is marked as required but not found

### ISSUE THREAD

**Issue by adhi54** [VLOGroup/dvs-panotracking#4]
I have ubuntu 16.04 installed and i'm using it as a remote user through 'ssh'. 
When I try building imageutilities it's ommittting GUI module as below
`-- The C compiler identification is GNU 4.9.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found suitable version "8.0", minimum required is "5.0") 
[+] ImageUtilities include IO module
  [-] build io module without Flycapture2/Pointgrey support
  [+] build io module with OpenEXR support
include dirs: /usr/include/usr/include/OpenEXR
[-] ImageUtilities omitting GUI module
[+] ImageUtilities include Math module
[-] do not build static library
Compiler Flags NVCC: -arch=sm_30-std=c++11
[-] insufficient gcc version, building without ndarray
NDARRAY_LIB=
additional iuio libs: /usr/lib/x86_64-linux-gnu/libHalf.so;/usr/lib/x86_64-linux-gnu/libIex.so;/usr/lib/x86_64-linux-gnu/libIlmImf.so;/usr/lib/x86_64-linux-gnu/libIlmThread.so;/usr/lib/x86_64-linux-gnu/libImath.so
install: /media/data/bimal/adhi/dvs-reconstruction/imageutilities
-- Found OpenEXR: /usr/lib/x86_64-linux-gnu/libHalf.so;/usr/lib/x86_64-linux-gnu/libIex.so;/usr/lib/x86_64-linux-gnu/libIlmImf.so;/usr/lib/x86_64-linux-gnu/libIlmThread.so;/usr/lib/x86_64-linux-gnu/libImath.so  
-- Configuring done
-- Generating done
-- Build files have been written to:/some/path/ `

And after this, when i try `cmake ../src ` to build the project, it's saying 
`iugui is marked as required but not found`

I think this is because I do not have display support for my system. 
Can you suggest what to do?
Is it possible for me to get the code without iugui module?

**Comment by reini1305** [comment]
Hi!

Sorry, I just saw your issue now. No, this is an interactive application. It is not possible to use it without display support.
