### ISSUE TITLE
Error while running live tracking gui terminate called after throwing an instance of 'std::logic_error'

### ISSUE THREAD

**Issue by asprasan** [VLOGroup/dvs-panotracking#5]
I installed all the required modules and dependencies. When I run the live_tracking_gui I am getting the following error: 

> terminate called after throwing an instance of 'std::logic_error'
> what():  basic_string::_S_construct null not valid

Since, I have limited knowledge of C++ any help to resolve the issue will be appreciated.

**Comment by reini1305** [comment]
Hi, did you start the GUI with the parameter specified in the README?
