### ISSUE TITLE
Update regarding libcaer

### ISSUE THREAD

**Issue by jasonjeong3** [VLOGroup/dvs-panotracking#6]
Is this compatible with the newer libcaer libraries?
I installed current updates of libcaer, but am having trouble linking the libcaer library in the cmake file. 
The new version of libcaer (3.3.8) seems to install at /usr/include/libcaer and /usr/lib/x86_64-linux-gnu/
where as the older version (2.0.0) installs at /usr/local/lib/ and /usr/local/inc/.
This seems to cause an error when building dvscameraworker.cpp;

`CMakeFiles/live_tracking_gui.dir/dvscameraworker.cpp.o: In function `DVSCameraWorker::run()':
dvscameraworker.cpp:(.text+0x289): undefined reference to `caerEventPacketContainerFree'
`

I tried changing the CMakeLists.txt in the src directory to the new directories, but this does not seem to work..
Is there a way I can still use the new libraries?

**Comment by reini1305** [comment]
Unfortunately, I was not able to test it with newer versions of libcaer. I've pinned the included library to the supported version. Is there a reason why you have to update? As far as I can see, both could exist on the system at the same time without interference.

**Comment by jasonjeong3** [comment]
I have newer versions of the event camera (DVXplorer and DAVIS240), which isn't supported in the pinned version of the library, and was hoping it'd be possible to run it on either the DVXplorer or the DAVIS240 by adding the header files in dvscameraworker.h file.

I was able to have it run on the DAVIS240 previously by using a newer libcaer library, but I can't seem to reproduce it..

Are there other portions of the code I'd need to change, other than the CMakeLists.txt in src dir, in order to link the newer libcaer library?

**Comment by reini1305** [comment]
Looking at your error message above and a quick glance at libcaer, it looks like the API changed a bit. I suspect that you might have to change the code in the DVS handler (https://github.com/VLOGroup/dvs-panotracking/blob/master/src/dvscameraworker.cpp#L27-L56). 

I'd love to see support for those newer devices in the code! I'd be happy to merge your changes once you are ready.

**Comment by reini1305** [comment]
I'm going to close this issue. If you manage to support a newer version of libcaer and DVS cameras, I'd love to accept your PR :)
