### ISSUE TITLE
tracking window resolution limitation?

### ISSUE THREAD

**Issue by SkyrimYun** [VLOGroup/dvs-panotracking#7]
Hi

I have successfully built this project and run the demo desk_swing.aer2 dataset with calib.txt under the default resolution 800 * 400.
Everything is all right until I changed the resolution from 800 * 400 to for example 2048*1024. then I got strange output like this:
![strange_output_dvs_panotracking](https://user-images.githubusercontent.com/36648778/119839449-7645ea80-bf04-11eb-9a4b-ce8fa21fec35.png)
It seems that the display is not working functionally in a higher resolution.
Is this some sort of bug or just a design feature?
Thanks a lot!

**Comment by reini1305** [comment]
Hi! 
Thanks for trying out the method. This gave me the chance to get it to run on my current machine after 4 years :)

The method is not completely independent from the size of the canvas it is doing the reconstruction on. If it is too large, the projected points are too sparse to get good gradients for the optimization. I played around a bit and got it to run until around 900x450 pixels. After that, it didn't converge, which is what you see above.

A possible workaround would be to draw the events bigger than 1 pixel or do the map update with small Gaussians around the event position. That way it should be possible to get to a higher resolution output.

**Comment by SkyrimYun** [comment]
Really appreciate your reply!
will try to apply what you advised.
